name: deploy-rust-lambda

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Build
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Package for Lambda
        run: |
          mkdir -p lambda_build
          cp target/x86_64-unknown-linux-gnu/release/presign lambda_build/bootstrap
          chmod +x lambda_build/bootstrap
          cd lambda_build && zip -r lambda.zip bootstrap

      - name: Deploy to Lambda
        uses: aws-actions/aws-cli@v2
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          args: |
            lambda update-function-code \
              --function-name s3-presign \
              --zip-file fileb://lambda_build/lambda.zip
