name: Deploy Rust Lambda Presign ARM64

on:
  push:
    branches: [ main ]
    
jobs:
  build-arm64:
    runs-on: ubuntu-22.04-arm
    defaults:
      run:
        working-directory: services/lambda-presign

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials          
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:           ap-northeast-2

      - name: Install musl and add Rust target
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
          rustup target add aarch64-unknown-linux-musl

      - name: Build static ARM64 binary
        run: |
          cargo build --release --target aarch64-unknown-linux-musl

      - name: Package Lambda artifact
        run: |
          mkdir -p deploy
          cp target/aarch64-unknown-linux-musl/release/presign deploy/bootstrap
          chmod +x deploy/bootstrap
          cd deploy
          zip -r presign-arm64.zip bootstrap

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name lambda-presign-arm64 \
            --zip-file fileb://deploy/presign-arm64.zip